name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  clone:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout master;
            git pull;