name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  clone:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Git Config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Just Pull
        run: git init && git checkout master && git pull && exit