name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  clone:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Just Pull
        run: |
          cd ~/test.atom-dev.ru/public_html/
          git checkout master;
          git pull;