name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  clone:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Just Pull
        run: git checkout master && git pull && exit
      - name: echos
        run: echo ${{ secrets.PROJECT_FOLDER }}